general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = true
    # We define the bezier curve first so it can be used by name
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    
    fade_in {
        duration = 300
        bezier = easeOutQuint
    }
    fade_out {
        duration = 300
        bezier = easeOutQuint
    }
}

background {
    path = ~/.cache/current_wallpaper
    blur_passes = 4
    blur_size = 4
    brightness = 0.5
}

input-field {
    monitor = 
    size = 15%, 5%
    outline_thickness = 5
    inner_color = rgba(30, 30, 46, 0.0)
    outer_color = rgb(116, 199, 236) rgb(148, 226, 213) 90deg
    check_color = rgb(f9e2af) rgb(fab387) 120deg
    fail_color = rgb(f38ba8) rgb(eba0ac) 40deg
    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15
    position = 0, -20
    halign = center
    valign = center
}

label {
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 128
    font_family = Adwaita Sans
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor = 
    text = $FPRINTPROMPT
    color = rgb(202, 211, 245)
    font_size = 14
    font_family = Adwaita Sans
    position = 0, -100
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = (Scan fingerprint to unlock)
    fingerprint:present_message = Scanning fingerprint
}
