# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  self,
  inputs,
  ...
}:
{
  flake.nixosModules.sanjiHardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    let
      imx471-module = config.boot.kernelPackages.callPackage (
        {
          stdenv,
          kernel,
          fetchFromGitHub,
        }:
        stdenv.mkDerivation {
          name = "imx471-${kernel.version}";
          passthru.moduleName = "imx471";

          src = fetchFromGitHub {
            owner = "BenBJD";
            repo = "imx471-dkms";
            rev = "11bd763d2f8feb64ce00cdab702542341ccaca50";
            sha256 = "sha256-w5ThydwfwUE1gnQCRoUJdYQiY8tpbDnZ1AqoS8gd+Go=";
          };

          hardeningDisable = [ "pic" ];
          nativeBuildInputs = kernel.moduleBuildDependencies;

          buildPhase = ''
            make -C ${kernel.dev}/lib/modules/${kernel.modDirVersion}/build M=$(pwd) modules
          '';

          installPhase = ''
            install -D imx471.ko $out/lib/modules/${kernel.modDirVersion}/misc/imx471.ko
            install -D ipu-bridge.ko $out/lib/modules/${kernel.modDirVersion}/misc/ipu-bridge.ko
          '';
        }
      ) { };
      libcamera-git = pkgs.libcamera.overrideAttrs (old: {
        version = "imx471-patched";

        src = pkgs.fetchgit {
          url = "https://github.com/gdamjan/libcamera.git";
          rev = "refs/heads/thinkpad-x9"; # Pulling the patched community branch
          hash = "sha256-GWqt/fFUthGu0MR4qdkOeca4pScd/8hhD5scf3DJTcs=";
        };

        # We will leave these here just in case this community branch
        # is also based on a newer commit that requires them.
        buildInputs = (old.buildInputs or [ ]) ++ [
          pkgs.elfutils
          pkgs.libyuv
          pkgs.libGL
        ];
      });
    in
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      # --- THE MAGIC TRICK ---
      # Inject the patched libcamera ONLY into the PipeWire media server.
      # This avoids rebuilding your whole OS, but gives native camera support to GNOME and Firefox!
      # services.pipewire = {
      #   enable = true;
      #   # ... keep your existing audio/pulse settings here ...
      #
      #   package = pkgs.pipewire.override {
      #     libcamera = libcamera-git;
      #   };
      #   wireplumber.package = pkgs.wireplumber.override {
      #     pipewire = pkgs.pipewire.override { libcamera = libcamera-git; };
      #   };
      # };

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [
        "kvm-intel"
        # "imx471"
        # "ipu-bridge"
      ];
      boot.kernelPackages = pkgs.linuxPackages_latest;
      # boot.extraModulePackages = [ imx471-module ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/64772fc4-75b5-4654-970b-9a37e0734140";
        fsType = "ext4";
      };

      fileSystems."/efi" = {
        device = "/dev/disk/by-uuid/3822-99F2";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/26E6-F56C";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      swapDevices = [
        {
          device = "/var/lib/swapfile";
          size = 32 * 1024; # 32 GiB
          options = [ "discard" ];
        }
      ];
      boot.zswap = {
        enable = true;
        #compressor = "lzo";
      };
      # zramSwap.enable = true;
      # services.earlyoom.enable = true;
      # services.earlyoom.extraArgs = [
      #   "--prefer" "(^|/)(.+-)?(firefox|teams)$"
      # ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

      environment.systemPackages = with pkgs; [
        sof-firmware
        alsa-utils # useful for testing later
        #libcamera-git
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

      hardware.enableAllFirmware = true;

      services.xserver.videoDrivers = [ "modesetting" ];
      hardware.graphics = {
        enable = true;
        extraPackages = with pkgs; [
          # Required for modern Intel GPUs (Xe iGPU and ARC)
          intel-media-driver # VA-API (iHD) userspace
          vpl-gpu-rt # oneVPL (QSV) runtime

          # Optional (compute / tooling):
          intel-compute-runtime # OpenCL (NEO) + Level Zero for Arc/Xe
          # NOTE: 'intel-ocl' also exists as a legacy package; not recommended for Arc/Xe.
          # libvdpau-va-gl       # Only if you must run VDPAU-only apps
        ];
      };

      environment.sessionVariables = {
        LIBVA_DRIVER_NAME = "iHD"; # Prefer the modern iHD backend
        # VDPAU_DRIVER = "va_gl";      # Only if using libvdpau-va-gl
      };

      # May help if FFmpeg/VAAPI/QSV init fails (esp. on Arc with i915):
      hardware.enableRedistributableFirmware = true;
      boot.kernelParams = [ "i915.enable_guc=3" ];
    };
}
